name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependências
        run: dotnet restore

      - name: Rodar linter
        run: dotnet format --verify-no-changes

      - name: Rodar testes com logger
        run: dotnet test --no-restore --verbosity normal \
          --logger "trx;LogFileName=test_results.trx"

      - name: Upload resultados de testes
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/test_results.trx"
# TO-DO
# Incuir notificações
# Incluir publicação de artefatos
# Incluir coberutura de código - Coverlet
